name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      target:
        description: "Publish target"
        required: true
        type: choice
        options:
          - testpypi
          - pypi

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v7
      - run: uv build
      - uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/

  pypi:
    needs: build
    if: github.event_name == 'push' || inputs.target == 'pypi'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/parch
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1

  testpypi:
    needs: build
    if: github.event_name == 'workflow_dispatch' && inputs.target == 'testpypi'
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/parch
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
